version: '3'

services:
  backend:
    build:
      app/backend
    command: [ 'flask', 'run', '--host=0.0.0.0', '--port=5000' ]
    volumes:
      - ./app/backend:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=application/app.py
    ports:
      - 5000:5000
    restart: unless-stopped

  frontend:
    build:
      app/frontend
    volumes:
    - ./app/frontend:/frontend
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  node-modules:
