name: Backend Unit Tests
on:
  push:
    paths:
      - 'app/backend/**'
      - '.github/workflows/backend-unit.yml'
jobs:
  ci:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          cd app/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd app/backend
          python -m pytest